# Generated by Django 3.1.2 on 2020-10-14 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='debtor_public',
            field=models.CharField(default='a9e3cfd9-e610-415b-95cd-96c39719bab3', max_length=255),
        ),
        migrations.AddField(
            model_name='ticket',
            name='owner_public',
            field=models.CharField(default='9e6b71d1-b37e-4eb1-b617-0fd5e9572024', max_length=255),
        ),
    ]
