# Generated by Django 3.1.2 on 2020-10-14 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20201014_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='debtor_public',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='owner_public',
        ),
    ]
