# Generated by Django 3.1.2 on 2020-10-17 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auto_20201014_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
