version: '3.5' # We use version 3.5 syntax

services: # Here we define our service(s)

    nginx-service:
        container_name: nginxardoisecontainer
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile
        environment:
            NODE_ENV: production
        ports:
            - 80:80

    ardoise-db:
        container_name: postgresardoisecontainer
        image: postgres
        environment: 
            - POSTGRES_DB=ardoise
            - POSTGRES_USER=ardoise
            - POSTGRES_PASSWORD=ardoise
        ports:
            - "54322:5432"

    django-service:
        container_name: djangoardoisecontainer
        build:
            context: .
            dockerfile: ./docker/django/Dockerfile
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - ./ardoise-serv:/usr/src/app
        ports:
            - 8000:8000



