# Generated by Django 3.1.2 on 2020-10-18 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ardoiseuser',
            table='ardoise_user',
        ),
    ]
