# Generated by Django 3.1.2 on 2020-10-18 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201018_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='ardoiseuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
