# Generated by Django 3.1.2 on 2020-10-18 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0010_auto_20201018_1609'),
        ('accounts', '0003_ardoiseuser_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='ardoiseuser',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.contact'),
        ),
    ]
