# Generated by Django 3.1.2 on 2020-10-17 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20201014_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='public_id',
            field=models.CharField(default='6d3d92c1-dc97-4b17-be83-4a0f31988598', max_length=255),
        ),
    ]
