# Generated by Django 3.1.2 on 2020-10-17 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_auto_20201017_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='public_id',
            field=models.CharField(default='ba93367d-caf0-42cd-97a0-5439f7a9caed', max_length=255),
        ),
    ]
