# Generated by Django 3.1.2 on 2020-10-18 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_auto_20201017_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='public_id',
            field=models.CharField(default='758e4137-fe52-4638-8bb8-75f636aa6a82', max_length=255),
        ),
    ]
