# Generated by Django 3.1.2 on 2020-10-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_auto_20201018_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='public_id',
            field=models.CharField(default='f1fa8fa3-bc27-4057-a3b9-8baafbc41610', max_length=255),
        ),
    ]
