# Generated by Django 3.1.2 on 2020-10-18 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_auto_20201018_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='public_id',
            field=models.CharField(default='3d5757ad-5045-4be7-b2c7-aa8edccaf921', max_length=255),
        ),
    ]
