# Generated by Django 3.1.2 on 2020-10-18 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0010_auto_20201018_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='public_id',
            field=models.CharField(default='9a311106-9540-46f2-8a8d-60811042d848', max_length=255),
        ),
        migrations.CreateModel(
            name='ContactRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactrelation_related_contact_a', to='contacts.contact')),
                ('contact_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactrelation_related_contact_b', to='contacts.contact')),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='contacts',
            field=models.ManyToManyField(related_name='_contact_contacts_+', through='contacts.ContactRelation', to='contacts.Contact'),
        ),
    ]
