# Generated by Django 3.1.2 on 2020-10-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0013_auto_20201018_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='public_id',
            field=models.CharField(default='43d97666-0dd3-4df4-ad82-3e1be3b43b40', max_length=255),
        ),
    ]
