# Generated by Django 3.1.2 on 2020-11-01 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0016_auto_20201031_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='public_id',
            field=models.CharField(default='7ce18df5-6cb0-429a-9ffd-698f1c4778e6', max_length=255),
        ),
        migrations.AlterField(
            model_name='invite',
            name='status',
            field=models.CharField(choices=[('IPE', 'Invitation pending'), ('IVA', 'Invitation validated'), ('ICA', 'invitation_cancelled'), ('IDE', 'invitation_denied')], default='IPE', max_length=50),
        ),
    ]
